firm:
  public:
    controller:     'public_demo'
    views:          'demo'
    layout:         'demo'
    page:
      title:        'Demo Ltd.'
      header:       'Demo motto'
      footer_text:  '&copy; 2005-2012 Demo Ltd.'
      footer_title: 'Ferenc-Loránt Kiss'
  system:
    page:
      title:        'TrustSys - Demo'
      header:       'TrustSys demo'
      footer_text:  '&copy; 2005-2012 kfl62'
      footer_title: 'Ferenc-Loránt Kiss'

  sass_dir:     'system/assets/stylesheets/demo'
  css_dir:      'public/stylesheets/demo'
  images_dir:   'public/images/demo'
  css_path:     '/stylesheets/demo'
  images_path:  '/images/demo'
  i18n_path:    'demo'

  db_devel:     'trst_demo'
  db_test:      'trst_test'
  db_prod:      'trst_demo'
